# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.network "private_network", ip: "192.168.33.11"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.name = "kafka08"
  end
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision :shell, path: "start-kafka.sh", run: "always"
end
